use md;

CREATE TABLE membres
(
    id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    salary INT(10) UNSIGNED NOT NULL
) 
ENGINE=InnoDb DEFAULT CHARSET=utf8 DEFAULT COLLATE utf8_unicode_ci;
